### ISSUE TITLE
libwmf crash on gimp

### ISSUE THREAD

**Issue by lillolollo** [caolanm/libwmf#2]
@caolanm Please read here https://gitlab.gnome.org/GNOME/gimp/issues/4061#note_628193

**Comment by lillolollo** [comment]
@caolanm Thanks for the quick response

**Comment by lillolollo** [comment]
@caolanm any ETA for a new release with the fix?

**Comment by lillolollo** [comment]
@caolanm ?

**Comment by caolanm** [comment]
0.2.13 was released
